# Exclude every file or folder starting with a dot.
exclude: ^\.

repos: 
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      # Harmonizing flake8 and black
      args: [
        '--max-line-length=88',
        '--ignore=E203,E731,E402,E501,E800,W503,F401',
        '--select=B,C,E,F,W,T4,B9'
      ]




